### ISSUE TITLE
Parameter file not recognized

### ISSUE THREAD

**Issue by IanLopesTeixeira** [mrueda/Beacon2#1]
Hello,

When running the test script, it doesn't recognize the parameter file, returning the help message.

ubuntu@beacon:~/Beacon2/test$ ../beacon vcf -i test_1000G.vcf.gz -p param.in
Option --p requires a param file
Usage:
    beacon <mode> [-arguments] [-options]

     Mode:
        info
           -h|help                        Brief help message
           -man                           Full documentation
           -v                             Version

         vcf
           -i|input                       Requires a VCF.gz file

         mongodb
                                          (May require a parameters file)

         full (vcf + mongodb)
           -i|input                       Requires a VCF.gz file
                                          (May require a parameters file)

         Options:
           -c                             Requires a configuration file
           -p                             Requires a parameters file
           -n                             Number of cpus/cores/threads
           -debug                         Print debugging (from 1 to 5, being 5 max)
           -verbose                       Verbosity on

           (For convenience, specifiers may have a leading - or --)

Thank you

**Comment by mrueda** [comment]
Hi Ian and thanks for reporting.

I just tested it in my machine and works fine:
```
mrueda@mrueda-ws1:~/test_beacon/github_issue/test$ date
Thu Mar 17 09:27:28 CET 2022
mrueda@mrueda-ws1:~/test_beacon/github_issue/test$ /pro/beacon/beacon vcf -i test_1000G.vcf.gz -p param.in 
Info:
Info: Beacon 2.0.0
Info: Beacon exe: /pro/beacon-2.0.0/beacon
Info: (C) 2021-2022 Manuel Rueda, PhD
Info: GNU General Public License v3
Info:
Info: ARGUMENTS USED:
Info: mode: vcf
Info: --i test_1000G.vcf.gz
Info: --p param.in
Info:
Info: CONFIGURATION VALUES:
Info: bash4bff          =>  /pro/beacon-2.0.0/BEACON/bin/run_vcf2bff.sh
Info: bash4html         =>  /pro/beacon-2.0.0/BEACON/bin/run_bff2html.sh
Info: bash4mongodb      =>  /pro/beacon-2.0.0/BEACON/bin/run_bff2mongodb.sh
Info: bcftools          =>  /pro/NGSutils/bcftools-1.11/bcftools
Info: bff2json          =>  /pro/beacon-2.0.0/BEACON/bin/bff2json.pl
Info: browserdir        =>  /pro/beacon-2.0.0/browser
```

The first thing that comes to my mind is that the param file is not a valid YAML. Are you using the latest version of the code?

Cheers,

m

**Comment by IanLopesTeixeira** [comment]
Thank you very much Manuel.

I installed the program yesterday, so I guess it's the latest. I didn't change a thing in the param.in, I only updated the values at the config.yaml. Could it be, because neither the variables genome and paneldir are not there?

Best regards,

Ian

**Comment by IanLopesTeixeira** [comment]
It looks just like this.
If I don't use the -p param.in, I get the error about bcftools being unable to find sequence 1 (the one you have at your README file).
Unfortunatelly, I can't acess the server where beacon is deploy tomorrow, only next Wednesday or Thursday. If you can then, it would be a great help.

Thank you again,

Ian

**Comment by mrueda** [comment]
Can you do it now?

**Comment by IanLopesTeixeira** [comment]
No sorry

**Comment by mrueda** [comment]
ok, let's schedule for next Thursday. I am available from 9-15h.

**Comment by IanLopesTeixeira** [comment]
Ok next Thursday. Just tell me what time zone are you referring?

**Comment by mrueda** [comment]
CET (Barcelona, Spain).

Drop me an email to the address you have in the README along with your preferred time and I will send you a Zoom invite. Thx.
