### ISSUE TITLE
Consider mapping of Variant caseLevelData for Individuals, Analyses and Runs

### ISSUE THREAD

**Issue by victorskl** [mrueda/Beacon2#15]
At the moment, this tool map `biosampleId` from VCF sample ID. And leave other caseLevelData null.

```
    "caseLevelData": [
      {
        "individualId": null,
        "biosampleId": "HG00128",
        "analysisId": null,
        "zigosity": null,
        "alleleOrigin": null,
        "clinicalInterpretations": null,
        "phenotypicEffects": null
      },
      ...
```

Beacon v2 implementation like [Java Beacon](https://doi.org/10.7490/f1000research.1118980.1); fetch associated meta info entities through this `caseLevelData` property. diito [snippet](https://gitlab.bsc.es/inb/ga4gh/beacon-v2-bsc/-/blob/master/beacon-nosql-server/src/main/java/es/bsc/inb/ga4gh/beacon/service/IndividualsService.java#L92)

Since this has missed during data transformation step (i.e. VCF to JSON) -- of which, IMO, is best to tackle this mapping -- the workaround like back-filling this data linkage will take awhile for some large cohort variant dataset.

Otherwise, application implementation could go through another route for fetching associated meta info for a variant. Then, Beacon spec might need to note this for a developer. (Just my opinion)

We demonstrate this with our demo setup avail at https://github.com/umccr/beacon-doc#demo-instance

---

BioSamples <> Variants

> This work.

```
curl -s 'https://faro.demo.umccr.org/beacon/v2.0.0/g_variants/chrchr22_10584988_G_A/biosamples' | jq
```

```
curl -s 'https://faro.demo.umccr.org/beacon/v2.0.0/biosamples/HG00097/g_variants?limit=10' | jq
```

---

Individuals <> Variants

> This won't work.

```
curl -s 'https://faro.demo.umccr.org/beacon/v2.0.0/g_variants/chrchr22_10584988_G_A/individuals' | jq
```

```
curl -s 'https://faro.demo.umccr.org/beacon/v2.0.0/individuals/HG00097/g_variants?limit=10' | jq
```

Just raising it here; to see if this observation useful.

/cc @reisingerf @ohofmann @mshadbolt

**Comment by mrueda** [comment]
Hi Victor,

Thanks for the comment. 

All BFF files are intermediate files. The fact that some properties are serialized/consolidated together is merely cosmetic. As far as I know, the ultimate responsibility of joining fields by key is left to each API implementation. One individual can contain many biosamples, and therefore the link between individual-biosamples must be carried out somewhere else.

CINECA / 1000G data are peculiar, as the labels on the VCF (`biosampleId`) are equal to `individualId`, but that's another story...

When building the Reference Implementation for the API, the developers already raised concerns about the complexity in resolving some of the API calls. These concerns were passed to the Beacon v2 API specification workgroup and some may lead to  future changes in the spec. If you have any concern in this regard (i.e., connection between entities via API calls), I recommend to raise the issue in the Beacon v2 [repo](https://github.com/ga4gh-beacon/beacon-v2). 

Hope this helps.

Cheers,

Manu

**Comment by victorskl** [comment]
Thanks for explanation and pointers, Manu. Appreciate it.

_(Side note: thanks for your tool. I was able to re-play transforming [the whole CINECA UK1 VCF](https://github.com/umccr/beacon-doc/tree/main/beacon/scratch/umccr_cineca_uk1). The only tinkering we did is - we lifted to Hg38.)_
