### ISSUE TITLE
Individuals.measures.measurementValue.inits - should be "unit"

### ISSUE THREAD

**Issue by redmitry** [mrueda/Beacon2#2]
Hello,

According the spec., the property is "unit" (not "units")
https://github.com/ga4gh-beacon/beacon-v2-Models/blob/cf394a7b7a7b409699c75b87337de5abd72764d2/BEACON-V2-Model/common/quantity.json#L7

Also see:
https://github.com/ga4gh-beacon/beacon-v2-Models/pull/67

Cheers,

Dmitry

**Comment by mrueda** [comment]
Hi Dmitry,

Thanks for pointing this out. The json files are created from an Excel template that still had `units` on the cell values. 

Interestingly, when changing `units` to `unit` something “darker” :smile: appeared. After the change, I noticed that I could not validate individuals’ data against the JSON schema anymore. After some deep hunting I figured that in [Phenopackets](https://phenopacket-schema.readthedocs.io/en/latest/quantity.html) unit/value should appear under the key `quantity`. This means that the [example](https://github.com/ga4gh-beacon/beacon-v2-Models/blob/main/BEACON-V2-Model/individuals/examples/individual-MID-example.json) provided in Github is wrong (that was the visual reference I used) and must be fixed (will do myself later). 

I already fixed my data in this repo. I consider this repo unrelased yet so all changes go to main.

Cheers!

m

**Comment by redmitry** [comment]
Hi Manuel,

I didn't get about "quantity" key...
~~~json
"measurementValue": {
    "description": "The result of the measurement",
    "oneOf": [{ "$ref": "./value.json" }, { "$ref": "./complexValue.json" }]
},
~~~
value.json;
~~~json
  "oneOf": [
    { "$ref" : "./quantity.json" },
    { "$ref" : "https://raw.githubusercontent.com/ga4gh-beacon/beacon-framework-v2/main/common/ontologyTerm.json" }
~~~
quantity.json:
~~~json
  "properties": {
    "unit": {
      "$ref": "./commonDefinitions.json#/definitions/Unit"
    },
    "value": {
      "description": "The value of the quantity in the units",
      "type": "number"
    },
~~~

So "unit" is a correct key here...

**Comment by mrueda** [comment]
Yes, I am referring to that one, which applies to the data I have in `individuals.json`.

See http://docs.genomebeacons.org/schemas-md/obj/measurementValue

m
